# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_transfer_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64\x61ta_transfer_api.proto\x12\x11\x64\x61ta_transfer_api\"\x18\n\x05Value\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"3\n\x12StoreValueResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1e\n\x0fGetValueRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"]\n\x10GetValueResponse\x12\x11\n\tkey_found\x18\x01 \x01(\x08\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x18.data_transfer_api.ValueH\x00\x88\x01\x01\x42\x08\n\x06_value\"I\n\x11StoreValueRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.data_transfer_api.Value2\xc5\x01\n\x0fKeyValueService\x12U\n\x08GetValue\x12\".data_transfer_api.GetValueRequest\x1a#.data_transfer_api.GetValueResponse\"\x00\x12[\n\nStoreValue\x12$.data_transfer_api.StoreValueRequest\x1a%.data_transfer_api.StoreValueResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_transfer_api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_VALUE']._serialized_start=46
  _globals['_VALUE']._serialized_end=70
  _globals['_STOREVALUERESPONSE']._serialized_start=72
  _globals['_STOREVALUERESPONSE']._serialized_end=123
  _globals['_GETVALUEREQUEST']._serialized_start=125
  _globals['_GETVALUEREQUEST']._serialized_end=155
  _globals['_GETVALUERESPONSE']._serialized_start=157
  _globals['_GETVALUERESPONSE']._serialized_end=250
  _globals['_STOREVALUEREQUEST']._serialized_start=252
  _globals['_STOREVALUEREQUEST']._serialized_end=325
  _globals['_KEYVALUESERVICE']._serialized_start=328
  _globals['_KEYVALUESERVICE']._serialized_end=525
# @@protoc_insertion_point(module_scope)
